# Generated by Django 6.0.6 on 2026-06-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_promogif'),
    ]

    operations = [
        migrations.AddField(
            model_name='promogif',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='promo_videos/'),
        ),
        migrations.AlterField(
            model_name='promogif',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='promo_images/'),
        ),
    ]
