# Generated by Django 6.0.6 on 2026-06-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_promogif_video_alter_promogif_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeforeAfter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('image_before', models.ImageField(upload_to='before_after/')),
                ('image_after', models.ImageField(upload_to='before_after/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
