# Generated by Django 6.0.6 on 2026-07-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0005_catalogpdf_contactrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogpdf',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='catalogs/covers/'),
        ),
    ]
