# Generated by Django 6.0.6 on 2026-07-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0006_catalogpdf_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogpdf',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
