# Generated by Django 6.0.6 on 2026-07-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0007_catalogpdf_download_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_secondary',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='تصویر دوم'),
        ),
    ]
