# Generated by Django 6.0.6 on 2026-07-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0008_product_image_secondary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homebanner',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='homebanner',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='position',
            field=models.CharField(choices=[('top', 'بالای صفحه'), ('bottom', 'پایین صفحه')], default='top', max_length=10),
        ),
    ]
