# Generated by Django 6.0.6 on 2026-07-08 08:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0009_alter_homebanner_options_homebanner_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogpdf',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_fa',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
