# Generated by Django 6.0.6 on 2026-07-08 09:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0010_alter_catalogpdf_download_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='description_en',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='brand',
            name='description_fa',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
