# Generated by Django 6.0.6 on 2026-07-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0011_alter_brand_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_new_packaging',
            field=models.BooleanField(default=False, help_text='فعال کنید تا روی کارت این محصول برچسب «بسته\u200cبندی جدید» نمایش داده شود.', verbose_name='بسته\u200cبندی جدید (New Emballage)'),
        ),
    ]
